version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    #environment:
    #  - MONGO_INITDB_ROOT_USER: mayur
    #  - MONGO_INITDB_ROOT_PASSWORD: secret
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    env_file:
      - ./env/backend.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - '2000:2000'
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - './frontend/src:/app/src'
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data: